### ISSUE TITLE
request for a topology

### ISSUE THREAD

**Issue by slatunje** [chuckbutler/flannel-docker-charm#10]
would it be possible for a ubuntu juju lxc/docker based diagram such as https://raw.githubusercontent.com/coreos/flannel/master/packet-01.png to help graps the concepts?

**Comment by lazypower** [comment]
Sure, thanks for the request @slatunje. I wont have time to address this in the upcoming week but it should be do-able the week afterwords. Unless another member of the team can address this before then. 

Cheers!

**Comment by lazypower** [comment]
@slatunje I've inserted a modified topology chart - as this currently only supports Docker (hense the flannel-docker name) Once this matures into a generic flannel service subordinate that can be attached to other container infrastructure I'll make sure we have additional charts drafted up for LXC.

As it stands now - its the exact same concept, only with lxcbr0 instead of docker0 as the interface name. The same virtual networking bridges are being created, and service pooling can be done in both platforms. The COREOS chart actually shows a Kubernetes pod deployed, with two containers making up each leg of the micro service.

However, I digress - if you need any further clarification don't hesitate to reach out.
